

build:crypto.cpp stocks.cpp valley.cpp ridge.cpp trigigel.cpp
	g++ crypto.cpp -o crypto
	g++ stocks.cpp -o stocks
	g++ valley.cpp -o valley
	g++ ridge.cpp -o ridge
	g++ trigigel.cpp -o trigigel

run-p1:
	./crypto

run-p2:
	./stocks

run-p3:
	./valley

run-p4:
	./ridge

run-p5:
	./trigigel

clean:
	rm crypto stocks valley ridge trigigel
