#include "Sequence.h"
int main()
{
    printf("FIRST TREE\n");
    Sequence tree = init();
    tree = insert(tree, 10, 0);
    tree = insert(tree, 212, 1);
    tree = insert(tree, 99, 2);
    tree = insert(tree, 54, 3);
    tree = insert(tree, 121, 4);
    tree = insert(tree, 31, 5);
    tree = insert(tree, 56, 6);
    tree = insert(tree, 75, 7);
    tree = insert(tree, 87, 8);
    printf("Size = %d\n", size(tree));
    preorder(tree);
    printf("\n");
    printf("LOOKUP(2)=%d\n", lookup(tree, 2));
    printf("Set(2)=100\n");
    set(tree, 100, 2);
    printf("LOOKUP(2)=%d\n", lookup(tree, 2));
    printf("SECOND TREE\n");
    Sequence tree2 = init();
    tree2 = insert(tree2, 9, 0);
    tree2 = insert(tree2, 10, 1);
    tree2 = insert(tree2, 11, 2);
    tree2 = insert(tree2, 12, 3);
    tree2 = insert(tree2, 13, 4);
    tree2 = insert(tree2, 14, 5);
    tree2 = insert(tree2, 15, 6);
    printf("Size = %d\n", size(tree2));
    preorder(tree2);
    printf("\nCONCAT\n");
    Sequence con = concat(tree, tree2);
    printf("Size = %d\n", size(con));
    preorder(con);
    printf("\n");
    printf("SPLIT\n");
    Sequence *sp = split(con, 5);
    printf("Lower : ");
    preorder(sp[0]);
    printf("\n");
    printf("Greater : ");
    preorder(sp[1]);
    printf("\n");
    printf("THIRD TREE\n");
    Sequence tree3 = init();
    tree3 = insert(tree3, 3, 0);
    tree3 = insert(tree3, 14, 1);
    tree3 = insert(tree3, 17, 2);
    tree3 = insert(tree3, 13, 3);
    tree3 = insert(tree3, 21, 4);
    tree3 = insert(tree3, 23, 5);
    printf("DELETE\n");
    printf("Size = %d\n", size(tree3));
    preorder(tree3);
    printf("\n");
    tree3 = delete (tree3, 3);
    printf("Size = %d\n", size(tree3));
    preorder(tree3);
    printf("\n");
    return 0;
}